import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import { EditorContext } from "@/lib/context/editor-machine-context";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${lora.variable} antialiased`}>
        <EditorContext>{children}</EditorContext>
      </body>
    </html>
  );
}
